name: azimutree
description: "Forest Health Monitoring Mapper"
publish_to: "none"
version: 1.1.26+26

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4 # Generates native Android/iOS splash screens from assets/config
  http: ^1.4.0 # Lightweight HTTP client for REST calls and network requests
  image_picker: ^1.1.2 # Capture images from camera or select from gallery
  intl: ^0.20.2 # Internationalization & date/number formatting utilities
  file_picker: ^10.1.9 # Cross-platform file selection (document import/export)
  excel: ^2.0.0 # Read/write Excel (.xlsx/.xls) files for data import/export
  path_provider: ^2.1.5 # Locate platform-specific directories (temp, documents, etc.)
  path: ^1.9.1 # Utilities for manipulating filesystem paths
  sqflite: ^2.4.2 # SQLite plugin for local relational storage and queries
  logger: ^2.5.0 # Structured logging helper with levels and outputs
  url_launcher: ^6.3.1 # Open URLs, phone dialer, email client, and external intents
  mapbox_maps_flutter: ^2.17.0 # Mapbox SDK: maps, layers, annotations and advanced rendering
  flutter_dotenv: ^6.0.0 # Load environment variables from a `.env` file securely
  cached_network_image: ^3.4.1 # Efficient image caching for remote images with placeholders
  flutter_slidable: ^3.1.0 # Adds swipe-to-reveal action panes (list item actions)
  shared_preferences: ^2.2.3 # Simple persistent key-value storage for small data
  geolocator: ^11.0.0 # Device location APIs: permissions, current position, streams

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_native_splash:
  color: "#1F4226" # Background color for native splash (hex for Color(0xFF1F4226))
  image: assets/images/splashscreen3.png # Splash image asset used for Android and iOS
  android: true
  ios: true

  android_12:
    image: assets/images/splashscreen3.png
    icon_background_color: "#1F4226"

# Configuration for flutter_launcher_icons to generate app icons from the
# provided asset. Running `flutter pub run flutter_launcher_icons:main`
# will generate platform-specific icons (Android mipmap and iOS AppIcon).
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/ic_launcher3.png
